package com.dmerc12.api.unit.entity;

import com.dmerc12.api.entity.AuditLog;
import org.hibernate.exception.ConstraintViolationException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.time.Instant;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@ActiveProfiles("test")
@DisplayName("Audit Log Entity Unit Tests")
public class AuditLogTests {

    @Autowired
    private TestEntityManager entityManager;

    private AuditLog createAuditLog() {
        AuditLog auditLog = new AuditLog();
        auditLog.setEventType("test-event");
        auditLog.setPrincipal("test-principal");
        auditLog.setUserAgent("test-user-agent");
        auditLog.setIpAddress("test-ip-address");
        auditLog.setTimestamp(Instant.now());
        auditLog.setData(Map.of("test", "test-data"));
        return auditLog;
    }

    @Nested
    @DisplayName("Column Mapping & Constraints")
    class ColumnMappingAndConstraintsTests {
        @Test
        @DisplayName("eventType is required")
        public void eventTypeIsRequired() {
            AuditLog auditLog = createAuditLog();
            auditLog.setEventType(null);
            assertThrows(
                    ConstraintViolationException.class,
                    () -> entityManager.persistAndFlush(auditLog)
            );
        }

        @Test
        @DisplayName("timestamp is required")
        public void timestampIsRequired() {
            AuditLog auditLog = createAuditLog();
            auditLog.setTimestamp(null);
            assertThrows(
                    ConstraintViolationException.class,
                    () -> entityManager.persistAndFlush(auditLog)
            );
        }

        @Test
        @DisplayName("ID is auto-generated")
        public void idIsAutoGenerated() {
            AuditLog auditLog = createAuditLog();
            assertNull(auditLog.getId());
            assertDoesNotThrow(
                    () -> entityManager.persistAndFlush(auditLog)
            );
            assertNotNull(auditLog.getId());
        }
    }

    @Nested
    @DisplayName("Field Optionality")
    class FieldOptionalityTests {
        @Test
        @DisplayName("principal can be null")
        public void principalCanBeNull() {
            AuditLog auditLog = createAuditLog();
            auditLog.setPrincipal(null);
            assertDoesNotThrow(
                    () -> entityManager.persistAndFlush(auditLog)
            );
            assertNull(auditLog.getPrincipal());
        }

        @Test
        @DisplayName("ipAddress can be null")
        public void ipAddressCanBeNull() {
            AuditLog auditLog = createAuditLog();
            auditLog.setIpAddress(null);
            assertDoesNotThrow(
                    () -> entityManager.persistAndFlush(auditLog)
            );
            assertNull(auditLog.getIpAddress());
        }

        @Test
        @DisplayName("userAgent can be null")
        public void userAgentCanBeNull() {
            AuditLog auditLog = createAuditLog();
            auditLog.setUserAgent(null);
            assertDoesNotThrow(
                    () -> entityManager.persistAndFlush(auditLog)
            );
            assertNull(auditLog.getUserAgent());
        }

        @Test
        @DisplayName("data can be null")
        public void dataCanBeNull() {
            AuditLog auditLog = createAuditLog();
            auditLog.setData(null);
            assertDoesNotThrow(
                    () -> entityManager.persistAndFlush(auditLog)
            );
            assertNull(auditLog.getData());
        }
    }

    @Nested
    @DisplayName("JSON Data Mapping (@JdbcTypeCode(SqlTypes.JSON))")
    class JSONDataMappingTests {
        @Test
        @DisplayName("Persist and retrieve JSON data")
        public void persistAndRetrieveJSONData() {
            AuditLog auditLog = createAuditLog();
            Map<String, Object> data = Map.of(
                    "uri", "/api/test",
                    "method", "POST",
                    "statusCode", 200
            );
            auditLog.setData(data);
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            Map<String, Object> retrievedData = found.getData();
            assertNotNull(retrievedData);
            assertEquals("/api/test", retrievedData.get("uri"));
            assertEquals("POST", retrievedData.get("method"));
            assertEquals(200, retrievedData.get("statusCode"));
        }

        @Test
        @SuppressWarnings("unchecked")
        @DisplayName("JSON with nested values")
        public void jsonWithNestedValues() {
            Map<String, Object> nested = Map.of("innerKey", "innerValue");
            Map<String, Object> data = Map.of(
                    "outerKey", "outerValue",
                    "nested", nested
            );
            AuditLog auditLog = createAuditLog();
            auditLog.setData(data);
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            Map<String, Object> retrieved = found.getData();
            assertNotNull(retrieved);
            assertEquals("outerValue", retrieved.get("outerKey"));
            Map<String, Object> retrievedNested = (Map<String, Object>) retrieved.get("nested");
            assertNotNull(retrievedNested);
            assertEquals("innerValue", retrievedNested.get("innerKey"));
        }
    }

    @Nested
    @DisplayName("Timestamp Mapping (Instant)")
    class TimestampMappingTests {
        @Test
        @DisplayName("Timestamp is stored and retrieved correctly")
        public void timestampIsStoredAndRetrievedCorrectly() {
            Instant before = Instant.now();
            AuditLog auditLog = createAuditLog();
            auditLog.setTimestamp(before);
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            assertEquals(before.toEpochMilli(), found.getTimestamp().toEpochMilli());
        }
    }

    @Nested
    @DisplayName("Basic CRUD")
    class BasicCRUDTests {
        @Test
        @DisplayName("Save and retrieve")
        public void saveAndRetrieve() {
            AuditLog auditLog = createAuditLog();
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            assertEquals(auditLog.getEventType(), found.getEventType());
            assertEquals(auditLog.getPrincipal(), found.getPrincipal());
        }

        @Test
        @DisplayName("Update")
        public void update() {
            AuditLog auditLog = createAuditLog();
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            assertEquals(auditLog.getEventType(), found.getEventType());
            assertEquals(auditLog.getPrincipal(), found.getPrincipal());
            found.setEventType("updated-event");
            found.setPrincipal("updated-principal");
            entityManager.persistAndFlush(found);
            entityManager.clear();
            AuditLog updated = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(updated);
            assertEquals("updated-event", updated.getEventType());
            assertEquals("updated-principal", updated.getPrincipal());
            assertEquals(auditLog.getTimestamp(), updated.getTimestamp());
        }

        @Test
        @DisplayName("Delete")
        public void delete() {
            AuditLog auditLog = createAuditLog();
            entityManager.persistAndFlush(auditLog);
            entityManager.clear();
            AuditLog found = entityManager.find(AuditLog.class, auditLog.getId());
            assertNotNull(found);
            entityManager.remove(found);
            entityManager.flush();
            entityManager.clear();
            AuditLog deleted = entityManager.find(AuditLog.class, auditLog.getId());
            assertNull(deleted);
        }
    }
}
