package com.dmerc12.api.repository;


import com.dmerc12.api.audit.JpaAuditEventRepository;
import com.dmerc12.api.entity.AuditLog;
import org.springframework.boot.actuate.audit.AuditEvent;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Repository interface for performing CRUD operations on {@link AuditLog} entities.
 * <p>This repository provides standard data access methods for audit log entries,
 * including save, find, and delete operations.
 * The repository is primarily used by the {@link JpaAuditEventRepository}
 * to persist audit events generated by Spring Security's audit framework.
 * <p>Spring Data JPA automatically implements this interface at runtime with appropriate
 * database operations based on the method naming conventions.
 *
 * @see AuditLog
 * @see AuditEvent
 * @see JpaAuditEventRepository
 */
@Repository
public interface AuditLogRepository extends JpaRepository<AuditLog, Long> {
}
