spring:
  profiles:
    active: dev # default profile
logging:
  level:
    com.dmerc12: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevOnly}
  expiration: 86400000

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finance-tracker}
    username: ${DB_USERNAME:finance-tracker}
    password: ${DB_PASSWORD:finance-tracker}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: health,info

---
# Test profile (uses H2 for fast testing)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
# Production profile (to be customized later)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finance-tracker}
    username: ${DB_USERNAME:finance-tracker}
    password: ${DB_PASSWORD:finance-tracker}
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
