package com.dmerc12.api.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.time.LocalDateTime;
import java.util.Set;

/**
 * Data Transfer Object for user information.
 * <p>This DTO is used as the response payload for user-related endpoints
 * (e.g., registration success, fetching user details, admin user management).
 * It excludes the password hash for security reasons.
 * <p><b>Usage:</b>
 * <ul>
 *     <li><b>Response:</b> Returned to the client after successful registration or profile fetch.</li>
 *     <li><b>User updates:</b> Used as a request body for updating user details (validation applies).</li>
 *     <li><b>Admin management:</b> Used as a request body for creating and updating user details
 *     (validation applies).</li>
 * </ul>
 * <p><b>Field notes:</b>
 * <ul>
 *     <li>{@code id}, {@code createdAt}, {@code updatedAt} are managed by the database and JPA.</li>
 *     <li>{@code roles} is a set of role strings (e.g., {@code "ROLE_USER"}) for frontend convenience.</li>
 * </ul>
 *
 * @see jakarta.validation.Validator
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserDTO {

    /**
     * The unique identifier of the user.
     * Auto-generated by the database.
     */
    private Long id;

    /**
     * The roles assigned to the user.
     * Stored as a set of role name strings (e.g., {@code "ROLE_USER"}).
     */
    private Set<String> roles;

    /**
     * The timestamp when the user was created.
     * Auto-set by JPA auditing.
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the user was last updated.
     * Auto-set by JPA auditing.
     */
    private LocalDateTime updatedAt;

    /**
     * The user's email address.
     * Must not be blank and must be a valid email format.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    private String email;

    /**
     * The user's first name.
     * Must not be blank and must not exceed 100 characters.
     */
    @NotBlank(message = "First name is required")
    @Size(max = 100, message = "First name cannot exceed 100 characters")
    private String firstName;

    /**
     * The user's last name.
     * Must not be blank and must not exceed 100 characters.
     */
    @NotBlank(message = "Last name is required")
    @Size(max = 100, message = "Last name cannot exceed 100 characters")
    private String lastName;
}
